sudo: required
language: java
notifications:
  email: false
jdk:
- openjdk8
services:
- docker
script:
- ".travis/build.sh $VERSION $COMMIT"
env:
  global:
  - TAG=2.13.0
  - VERSION=2.13.0
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: Ykf1DTNPG1awPnuO8LwHgsQQkdeANgg/yf+dHg+URgzfBDovavhYK4AoQuB5TIU/3+ENGTChfUExbR/4llQRjqI/e1UyJwY/Oh6Ymq7pgNbQmCW6TV2wJKbGLiM1h+pV2crlrjeS57G+yoKy9MypLPOM1M75OwKMZaqCO2QM7Vqlzu4C9i5DDyaPFZ0t3rGw27DfWtKDDBYelQnyiDcQBSktNQb3DkZi4hiIjkpIgPE+Ag7gwPavqathyRRGCoimCspggO6PXesLzvh+3/ki+q7UL+z9YxZ2tYXU73O29yB9cY58XowEyZHWmxwkH+myMlbRTygA3znFkpBWzVbJg+5A98WMcBoe3kjO7P+F5zp1Q+4096TgxURTJ1p7PKlNwl+7q2ep8tZ4rB/Xu4L+Hsm8YMxAKtue5Jb0LFefpkctVCY+Ej3/FEJyvQvcqIYx44H0OSYivu2K9buk0TnXmFry6vE1CP6tFGJQmsVNGT970URZ9ZuDpvAKwZ7w1jhgUcmBZHsXeVUt/D2njTZLv154dozgsztJs1V9EzgCplanrUMP7EFkuAnjx8ItU+modtei/BCJHEAJWTPovUFNKI+JcpJ5CEv/zGaB0PPNOmbs+lUBGPn00wErcZLrYap/C5sG6OVKva34QU7DBEQUyoNP/bMjixyYA6t/C0XonwE=
  - secure: NeELrK5eROcnteD/LmRwjhXEUbZe951+0eo18+Q6zJ6KodvMgUmM3VVKiaLgu/AbODf+8CC3C/EL8yRZdnIhIShtMkgg0Vg7nFTctwTAKUeWI7ltW7ifbMiD4zp2gZCPjkzN6fdNVkjwb8JKpCQw4g72KodaJUjIAotH01hP6pVLglWxV7iRrwRJRpSNxfWe4wQIIjHehmKTnSSNGq16eRM+0akKLICu3efZZcZ2cJuiYCLxNFBb2mUpC53EkzYQP+o4Bij4KGDnkx5yJ4CewW3Dy8F2/lAkQaSf76ARMjPQ6T2lCnXoaq1Ge+PXlQTqDe0Iak0NlA7aiVt4u89wA39LmsSBIh2uZ3aEouZK+6QyRgfI2kqYFnxKzKaNMz5q154pfSRf1OzlLWLNm/rYZT6MA4JMXVyiwrTYrhBNVy4qE9pALmTCBjLBJZdrde0sky7GPl6zvYu/fzfoZRiyLsqOpY7KMOrveN/9zFk1UH7Ea/8o/kDoZw/2XHH8eCqZr8UAinTUdTewOuHhGJumBDH/C+oeD94G58mKRgxnfEix6gayPGaU2pbRmK6bWX317ujv4uEEULWkd1V7tgGXnpqAmbUqsikasPG5Rmzy7jHs2x+qw7lWQWTB+eT79uV0Jwhbw54bOYUuIqVJP+JxTcx2XfeDIbKJqaIlqvhu8GE=
